# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160915_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='count_of_users',
            field=models.IntegerField(null=True),
        ),
    ]
