# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_register_count_of_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='count_of_users',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
