# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160916_0118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Count',
        ),
    ]
